TaskHub.Web/Controllers/TasksController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using TaskHub.Web.Filters;
using TaskHub.Web.Models;
using WebMatrix.WebData;
using Newtonsoft.Json;

namespace TaskHub.Web.Controllers
{
    [Authorize]
    public class TasksController : Controller
    {
        private ITaskHubContext db = new TaskHubEntities();

        public TasksController() { }
        public TasksController(ITaskHubContext context)
        {
            db = context;
        }
        //
        // GET: /Tasks/
        [InitializeSimpleMembership]
        public ActionResult Index(string searchString)
        {
            if(User.IsInRole("Admin"))
            {
                var tasks = FetchTasks(searchString);
                ViewBag.CurrentFilter = searchString;
                return View(tasks.ToList());
            }
            else
            {
                int userid = (int)Membership.GetUser().ProviderUserKey;
                var tasks = FetchTasks(searchString, userid);
                ViewBag.CurrentFilter = searchString;
                return View("Index", tasks.ToList());
            }

        }

        public IQueryable<Tasks> FetchTasks(string searchString, int userId = 0)
        {
            var tasks = db.Tasks.Where(t => t.Status != "Closed").Include(t => t.AssignedUser).Include(t => t.RequestedUser);
            if (userId > 0)
                tasks = tasks.Where(t => t.AssignedTo == userId);
            if (!String.IsNullOrEmpty(searchString))
            {
                tasks = tasks.Where(t => t.Title.Contains(searchString) || t.AssignedUser.UserName.Contains(searchString) || t.Priority.Contains(searchString) || t.Status.Contains(searchString));
            }
            return tasks;
        }

        public IEnumerable<Tasks> GetAllTasks()
        {
            var res = db.Tasks.ToList();
            return res;
        }

       //
        // GET: /Tasks/Details/5

        public ActionResult Details(Guid id)
        {
            Tasks tasks = db.Tasks.Find(id);
            if (tasks == null)
            {
                return HttpNotFound();
            }
            return View(tasks);
        }

        //
        // GET: /Tasks/Create
        public ActionResult Create()
        {
            ViewBag.AssignedTo = new SelectList(db.UserProfile, "UserId", "UserName");
            ViewBag.RequestedBy = new SelectList(db.UserProfile, "UserId", "UserName");
            return View();
        }

        [HttpGet]
        public ActionResult GetTasksbySearchString(string search)
        {
            var tasksByStatus = db.Tasks.Where(t => t.Title.Contains(search)).Include(t => t.AssignedUser).Include(t => t.RequestedUser).ToList();
            List<TaskHub.Web.Messages.Task> tasks = new List<TaskHub.Web.Messages.Task>();
            foreach (var tp in tasksByStatus)
            {
                var t = new TaskHub.Web.Messages.Task();
                t.Title = tp.Title;
                t.Status = tp.Status;
                t.Priority = tp.Priority;
                t.TaskId = tp.TaskId;
                t.DueDate = tp.DueDate;
                tasks.Add(t);

            }
            return Json(tasks, JsonRequestBehavior.AllowGet);
        }

         //
        // POST: /Tasks/Create

        [HttpPost]
        public ActionResult Create(Tasks tasks)
        {
            if (ModelState.IsValid)
            {
                tasks.TaskId = Guid.NewGuid();
                
                db.Tasks.Add(tasks);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.AssignedTo = new SelectList(db.UserProfile, "UserId", "UserName", tasks.AssignedTo);
            ViewBag.RequestedBy = new SelectList(db.UserProfile, "UserId", "UserName", tasks.RequestedBy);
            ViewBag.LastModifiedDate = DateTime.Now;
            return View(tasks);
        }

        //
        // GET: /Tasks/Edit/5

        public ActionResult Edit(Guid id)
        {
            Tasks tasks = db.Tasks.Find(id);
            if (tasks == null)
            {
                return HttpNotFound();
            }
            var users = db.UserProfile;
            ViewBag.Users = db.UserProfile;
            ViewBag.AssignedTo = new SelectList(users, "UserId", "UserName", tasks.AssignedTo);
            ViewBag.RequestedBy = new SelectList(users, "UserId", "UserName", tasks.RequestedBy);
           
            return View(tasks);
        }

        //
        // POST: /Tasks/Edit/5

        [HttpPost]
        public ActionResult Edit(Tasks tasks)
        {
            if (tasks.AssignedUser == null)
                tasks.AssignedUser = db.UserProfile.First(u => u.UserId == tasks.AssignedTo);
            if (tasks.RequestedUser == null)
                tasks.RequestedUser = db.UserProfile.First(u => u.UserId == tasks.RequestedBy);
                  
            tasks.LastModifiedDate = DateTime.Now;
            var errors = ModelState.Values.SelectMany(v => v.Errors);
            if (ModelState.IsValid)
            {
                db.MarkAsModified(tasks);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.AssignedTo = new SelectList(db.UserProfile, "UserId", "UserName", tasks.AssignedTo);
            ViewBag.RequestedBy = new SelectList(db.UserProfile, "UserId", "UserName", tasks.RequestedBy);
            return View(tasks);
        }

        //
        // GET: /Tasks/Delete/5

        public ActionResult Delete(Guid id)
        {
            Tasks tasks = db.Tasks.Find(id);
            if (tasks == null)
            {
                return HttpNotFound();
            }
            return View(tasks);
        }

        //
        // POST: /Tasks/Delete/5

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(Guid id)
        {
            Tasks tasks = db.Tasks.Find(id);
            db.Tasks.Remove(tasks);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

TaskHub.Web/Controllers/UsersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TaskHub.Web.Models;

namespace TaskHub.Web.Controllers
{
    public class UsersController : Controller
    {
        private TaskHubEntities db = new TaskHubEntities();

        //
        // GET: /Users/

        public ActionResult Index()
        {
            return View(db.UserProfile.ToList());
        }

        //
        // GET: /Users/Details/5

        public ActionResult Details(int id = 0)
        {
            UserProfile userprofile = db.UserProfile.Find(id);
            if (userprofile == null)
            {
                return HttpNotFound();
            }
            return View(userprofile);
        }

        //
        // GET: /Users/Create

        public ActionResult Create()
        {
            return View();
        }

        //
        // POST: /Users/Create

        [HttpPost]
        public ActionResult Create(UserProfile userprofile)
        {
            if (ModelState.IsValid)
            {
                db.UserProfile.Add(userprofile);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(userprofile);
        }

        //
        // GET: /Users/Edit/5

        public ActionResult Edit(int id = 0)
        {
            UserProfile userprofile = db.UserProfile.Find(id);
            if (userprofile == null)
            {
                return HttpNotFound();
            }
            return View(userprofile);
        }

        //
        // POST: /Users/Edit/5

        [HttpPost]
        public ActionResult Edit(UserProfile userprofile)
        {
            if (ModelState.IsValid)
            {
                db.Entry(userprofile).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(userprofile);
        }

        //
        // GET: /Users/Delete/5

        public ActionResult Delete(int id = 0)
        {
            UserProfile userprofile = db.UserProfile.Find(id);
            if (userprofile == null)
            {
                return HttpNotFound();
            }
            return View(userprofile);
        }

        //
        // POST: /Users/Delete/5

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            UserProfile userprofile = db.UserProfile.Find(id);
            db.UserProfile.Remove(userprofile);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

TaskHub.Web/Views/Shared/_Layout.cshtml
    <!DOCTYPE html>
    <html lang="en">
        <head>
            <meta charset="utf-8" />
            <meta name="viewport" content="width=device-width, initial-scale=1.0" />
            <title>TasksHub Application</title>
            <link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />
            <meta name="viewport" content="width=device-width" />
            @Styles.Render("~/Content/css")
            @Scripts.Render("~/bundles/modernizr")
    	    <link rel="stylesheet" type="text/css" href="@Url.Content("~/Content/bootstrap.min.css")" />
	        <link rel="stylesheet" type="text/css" href="@Url.Content("~/Content/bootstrap-theme.min.css")" />
            <link rel="stylesheet" type="text/css" href="@Url.Content("~/Content/datepicker.css")"  />
	        <link rel="stylesheet" type="text/css" href="http://code.jquery.com/ui/1.9.2/themes/base/jquery-ui.css">
	        <link rel="stylesheet" type="text/css" href="@Url.Content("~/Content/app.css")">
	<script src="https://code.jquery.com/jquery.js"></script>
	<script src="http://code.jquery.com/ui/1.9.2/jquery-ui.js"></script>
	<script type="text/javascript" src="~/scripts/bootstrap.min.js"></script>
	        <script type="text/javascript" src="@Url.Content("~/Scripts/app.js")"></script>
            
            <script type="text/javascript">
                (function ($) {
                    $(document).ready(function () {
                        $(".date-picker").datepicker();
                    });
                })(jQuery);
    </script>
        </head>
        <body>
                <div  class="header-nav navbar navbar-inverse navbar-default" role="navigation">
		    <div class="container">
            <div class="navbar-header">
              <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
    		    <span class="sr-only">Toggle navigation</span>
		        <span class="icon-bar"></span>
		        <span class="icon-bar"></span>
		        <span class="icon-bar"></span>          
		    </button>
              <a class="navbar-brand" href="#"><img class="hdr-logo" src="@Url.Content("~/Content/Images/header-logo.jpg")" alt="Header Logo" title="Header Logo" /></a>
            </div>
            <div class="navbar-collapse collapse" style="height: 1px;">
              <ul class="nav navbar-nav">
                  @if(User.Identity.IsAuthenticated){
                <li  class="active"><a href="@Url.Action("Index","Tasks")">Tasks</a></li>
                  }
                  @if (User.IsInRole("Admin"))
                  {
                <li><a href="@Url.Action("Index","Users")">Users</a></li>
                  }
              </ul>
              <div class="nav navbar-nav navbar-right">
              <!--  <li><a href="@Url.Action("Create")"><span class="glyphicon glyphicon-plus"></span>Create Task</a></li>-->
               <!-- <li><a href="#"><span class="glyphicon glyphicon-log-out"></span>  Logout</a></li>-->
            @Html.Partial("_LoginPartial")
              </div>
            </div><!--/.nav-collapse -->
          </div>
	    </div>
                @RenderSection("featured", required: false)
                    @RenderBody()
               

                       
            @Scripts.Render("~/bundles/jquery")
            @RenderSection("scripts", required: false)
        </body>
    </html>